spring:
  datasource:
    url: jdbc:mysql://xxxxx:10048/t66y
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    listener:
      simple:
        concurrency: 10

#logging:
#  level:
#    root: debug

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lizhao.lianjiatj.entity.dao

constant:
  rabbit:
    url:
      routing-key: sendUrl
      exchange: lianjia
    receiveResult:
      routing-key: reciveResult
      exchange: lianjia
